[package]
name = "bpm-is"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
instant = { version = "0.1", features = [ "wasm-bindgen" ] }